---
apiVersion: v1
data:
  accessToken: Z2l0aHViX3BhdF8xMUFCWkpPTUEwYjlBODFOYXYwZ2dlX1JESXRoNXROT3BOVHdtTFRqNnBvdXdXeDNpdFFySUlzY2hFWURWb2J0b1dMV0RNRkVUQllESVNTM3VF
  user: IGdpYW5uaXNhbGluZXR0aQ==
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/serving-channel: ztp-sno/ggithubcom-redhat-italy-summit-ztp-edge
  labels:
    apps.open-cluster-management.io/serving-channel: "true"
    cluster.open-cluster-management.io/backup: app
  name: ggithubcom-redhat-italy-summit-ztp-edge-auth
  namespace: ztp-sno
type: Opaque
