---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ztp-sno-subscription-1
  namespace: ztp-sno
  annotations:
    apps.open-cluster-management.io/git-branch: 'main'
    apps.open-cluster-management.io/git-path: 'spoke'
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: ztp-sno
spec:
  channel: ztp-sno/ggithubcom-redhat-italy-summit-ztp-edge
  placement:
    placementRef:
      name: ztp-sno-placement-1
      kind: PlacementRule
posthooks: {}
prehooks: {}
