---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-redhat-italy-summit-ztp-edge
  namespace: ztp-sno
spec:
  pathname: https://github.com/redhat-italy/summit-ztp-edge.git
  secretRef:
    name: ggithubcom-redhat-italy-summit-ztp-edge-auth
  type: Git
