apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ztp-sno
  namespace: ztp-sno
  labels:
    name: ztp-sno
    region: "Rome"
    sno: "true"
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 120
