apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  name: provisioning-configuration
spec:
  preProvisioningOSDownloadURLs: {}
  provisioningNetwork: Disabled
  provisioningOSDownloadURL: "PUT A QCOW2 IMAGE + SHA256SUM"
  virtualMediaViaExternalNetwork: true
  watchAllNamespaces: true
